#!/usr/bin/env python

##### LOADING IN PACKAGES #--------------------------------------------------------------
import s3fs; import xarray as xr; import numpy as np
import pandas as pd; 
import dask.array as da
import ocetrac

import matplotlib.pyplot as plt; import cartopy.crs as ccrs

import warnings; import expectexception
warnings.filterwarnings('ignore')

import netCDF4 as nc; import datetime as dt
import scipy

import intake; import pprint
# Allow multiple lines per cell to be displayed without print (default is just last line)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# Enable more explicit control of DataFrame display (e.g., to omit annoying line numbers)
from IPython.display import HTML

ds_blob = xr.open_dataset("blobs_sample.nc")
ds_detrendedSSTA = xr.open_dataset("detrended_sample.nc")

ds_blob
ds_detrendedSSTA

label = ds_blob.variables['labels'][:]
ssta = ds_detrendedSSTA.variables['__xarray_dataarray_variable__'][:]
blob.shape
ssta.shape
