#!/usr/bin/env python

# https://gallery.pangeo.io/repos/NCAR/cesm-lens-aws/notebooks/EnhancedIntakeCatalogDemo.html

##### Set up environment
# Done on test-env where intake-esm was installed via: 
#   conda create -n test-env -c conda-forge dask distributed ipython netcdf4 xarray intake-esm 
#   conda activate test-env

import intake
import pandas as pd
import pprint
# Not used here:
###import numpy as np
###import xarray as xr
# Allow multiple lines per cell to be displayed without print (default is just last line)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# Enable more explicit control of DataFrame display (e.g., to omit annoying line numbers)
from IPython.display import HTML

##### Inspect original intake-esm catalog
# Open original collection description file
cat_url_orig = 'https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-le.json'
coll_orig = intake.open_esm_datastore(cat_url_orig)

col_subset = coll_orig.search(frequency=["monthly"], component="ocn", variable="SST",
                        experiment=["20C", "RCP85"])
col_subset
col_subset.df

# Help from https://github.com/intake/intake-esm/issues/148
# Load catalog entries for subset into a dictionary of xarray datasets
dsets = col_subset.to_dataset_dict(zarr_kwargs={"consolidated": True}, storage_options={"anon": True})
print(f"\nDataset dictionary keys:\n {dsets.keys()}")

print(dsets)

# Define Xarray datasets corresponding to the three experiments
ds_20C = dsets['ocn.20C.monthly']
ds_RCP85 = dsets['ocn.RCP85.monthly']

# https://gallery.pangeo.io/repos/NCAR/cesm-lens-aws/notebooks/kay-et-al-2015.v3.html

##### Use Dask.Distributed utility function to display size of each dataset
from distributed.utils import format_bytes
print(f"20th Century: {format_bytes(ds_20C.nbytes)}\n"
      f"RCP8.5: {format_bytes(ds_RCP85.nbytes)}")

# Extract the Reference Height Temperature data variable
t_20c = ds_20C.TEMP.isel(member_id=0,z_t=0) #looking at one ensemble member (the first one)
t_rcp = ds_RCP85.TEMP.isel(member_id=0,z_t=0)
t_20c
